import './globals.css';

import { Sora } from 'next/font/google';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const sora = Sora({
    subsets: ['latin'],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={sora.className}>
            <body>{children}</body>
        </html>
    );
}
